services:
  backend:
    build: ./backend/
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
    - BACKEND_NODE_ENV=${BACKEND_NODE_ENV}
    - BACKEND_HOST=${BACKEND_HOST}
    - BACKEND_PORT=${BACKEND_PORT}
    - BACKEND_JWT_SECRET=${BACKEND_JWT_SECRET}
    depends_on:
      - db
  db:
    image: postgres:16.4
    ports:
      - "${BACKEND_DATABASE_PORT}:${BACKEND_DATABASE_PORT}"
    environment:
      - POSTGRES_USER=${BACKEND_DATABASE_USER}
      - POSTGRES_PASSWORD=${BACKEND_DATABASE_PASSWORD}
      - POSTGRES_DB=${BACKEND_DATABASE_NAME}